export const relationshipTypeArray = [
  'Friend',
  'son',
  'daughter',
  'brother',
  'sister',
  'girlfriend',
  'boyfriend',
  'wife',
  'husband',
  'fiance',
  'fiancée',
  'father',
  'mother',
  'grandparent',
  'cousin',
  'colleague',
  'mother-in-law',
  'father-in-law',
  'aunt',
  'uncle',
  'extended family',
  'other',
];
export const daysArray = Array.from(Array(32).keys());

export const monthsArray = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];
